server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping_mall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 060629
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

grpc:
  server:
    port: 50051

app:
  jwt:
    # Must match api_gateway config.local.yml jwt.secret
    secret: "dev-jwt-secret-change-me-use-at-least-32-bytes!!"
    expiration: 86400000

logging:
  level:
    root: INFO

oss:
  bucket-name: